package security.planck.mdm

import com.fsck.k9.auth.OAuthProviderType

const val DEFAULT_PROVISIONING_URL = "https://provisioning.pep.security/{{partialupn}}/pEp.ppk"
const val DEFAULT_PRIVACY_PROTECTION = true
const val DEFAULT_EXTRA_KEY = ""
const val DEFAULT_MEDIA_KEY_PATTERN = ""
const val DEFAULT_MEDIA_KEY_FPR = ""
const val DEFAULT_MEDIA_KEY_MATERIAL = ""
const val DEFAULT_UNSECURE_DELIVERY_WARNING = true
const val DEFAULT_PLANCK_SYNC_FOLDER = true
const val DEFAULT_PLANCK_DEBUG_LOG = false
const val DEFAULT_ENABLE_ECHO_PROTOCOL = false
const val DEFAULT_ACCOUNT_DESCRIPTION = "{{mail}}"
const val DEFAULT_ACCOUNT_COMPOSITION_SENDER_NAME = "{{username}}"
const val DEFAULT_ACCOUNT_COMPOSITION_USE_SIGNATURE = true
const val DEFAULT_ACCOUNT_COMPOSITION_SIGNATURE = "--  Sent from planck for Android. "
const val DEFAULT_ACCOUNT_COMPOSITION_SIGNATURE_BEFORE_QUOTED_MESSAGE = false
const val DEFAULT_ACCOUNT_LOCAL_FOLDER_SIZE = "250"
const val DEFAULT_ACCOUNT_MAX_PUSH_FOLDERS = "25"
const val DEFAULT_ACCOUNT_QUOTE_MESSAGES_REPLY = true
const val DEFAULT_FOLDER = ""
const val DEFAULT_ACCOUNT_ENABLE_SERVER_SEARCH = true
const val DEFAULT_ACCOUNT_SERVER_SEARCH_LIMIT = 50
const val DEFAULT_ACCOUNT_ENABLE_SYNC = true
const val DEFAULT_ACCOUNT_EMAIL_ADDRESS = "{{mail}}"
val DEFAULT_ACCOUNT_OAUTH_PROVIDER = OAuthProviderType.MICROSOFT.toString()
const val DEFAULT_ACCOUNT_MAIL_SETTINGS_SERVER = ""
const val DEFAULT_ACCOUNT_MAIL_SETTINGS_USER_NAME = "{{mail}}"
const val DEFAULT_ACCOUNT_INCOMING_MAIL_SETTINGS_PORT = 993
const val DEFAULT_ACCOUNT_OUTGOING_MAIL_SETTINGS_PORT = 587
const val DEFAULT_ACCOUNT_INCOMING_MAIL_SETTINGS_SECURITY = "SSL/TLS"
const val DEFAULT_ACCOUNT_OUTGOING_MAIL_SETTINGS_SECURITY = "STARTTLS"
val DEFAULT_ACCOUNT_MAIL_SETTINGS_AUTH_TYPE = AuthType.PLAIN.toString()
const val DEFAULT_AUDIT_LOG_DATA_TIME_RETENTION = "2592000"
