@startuml
skinparam ranksep 20
skinparam dpi 125
skinparam packageTitleAlignment left
skinparam linetype ortho
'left to right direction


rectangle "Compose Message" {
    (Calculate message\nsecurity status) as (cmss)
    (Calculate recipents\nsecurity status) as (crss)
    (Remove unsecure\nrecipients) as (rur)
    (Add and Remove\nRecipients) as (aarr)
    (Send message) as (sm)
    note bottom of (sm)
    detailed in
    diagram/page xxx
    end note
    (Display recipients\nsecurity status) as (drss)
    (Display message\nsecurity status) as (dmss)
    (Establish trust with\nsecure recipients) as (etwsr)
    note bottom of (etwsr)
    detailed in
    diagram/page xxx
    end note
}

user ---> (sm)
user ---> (rur)
user ---> (etwsr)
user ---> (aarr)


app -up---> (sm)
app -up---> (dmss)
app -up---> (drss)
app -up---> (cmss)
app -up---> (crss)
app -up---> (rur)
app -up---> (etwsr)
app -up---> (aarr)


(cmss) <--- core
(crss) <--- core


(drss) ........> (crss) : <<includes>>
(dmss) ........> (cmss) : <<includes>>
@enduml
